import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "SoftRestaurant Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-slate-200">
          <main className="">
              {children}
          </main>
      </body>
    </html>
  );
}
